opencl_impl:
  - icdloader
  - icdsystem
# cuda_impl:
#   - cudatoolkit
#   - systemcuda
cuda_compiler_version:
  - "10.2"
docker_image:
  - condaforge/linux-anvil-cuda:10.2
python:
  - 3.8.* *_cpython
channel_targets:
  - openmm testing
