conda_forge_output_validation: true
github:
  user_or_org: openmm
azure:
  org_or_user: openmm
channels:
  targets:
    - ["openmm", "testing"]
provider:
  linux: azure
  osx: azure
  win: False
  linux_ppc64le: False
  linux_aarch64: False
