# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      osx_opencl_implicdloader:
        CONFIG: osx_opencl_implicdloader
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.2
      osx_opencl_implicdsystem:
        CONFIG: osx_opencl_implicdsystem
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-cuda:10.2
    maxParallel: 8
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      # make sure there is a package directory so that artifact publishing works
      mkdir -p /usr/local/miniconda/conda-bld/osx-64/
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)

  - publish: /usr/local/miniconda/conda-bld/osx-64/
    artifact: conda_pkgs_osx